# Undeploy
---
- name: Undeploy website on port 8080
  hosts: all
  user: root
  
  tasks:
    - name: stop nginx
      service:
         name: nginx
         state: stopped
    
    - name: Remove index.html
      file:
        path: /usr/share/nginx/html/index.html
        state: absent
    
    - name: Remove nginx.conf
      file:
        path: /etc/nginx/nginx.conf
        state: absent  
    
    - name: uninstall nginx
      yum:
        name: nginx
        state: absent
        
    - name: uninstall epel-release
      yum:
        name: epel-release
        state: absent
        
    - name: disable port 8080
      firewalld:
        port: 8080/tcp
        zone: public
        permanent: yes
        state: disabled

    - name: Reload Firewall
      service:
       name: firewalld
       state: restarted
